---

version: "3"

services:

  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    networks:
      - mongo

  zucchini-ui:
    image: "pgentile/zucchini-ui:${ZUCCHINI_VERSION:-latest}"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ZUCCHINI_MONGO_URL: "mongodb://mongo/zucchini?w=majority&journal=true"
    links:
      - mongo
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
